using System;using System.Collections;using System.IO;using System.Linq;using System.Reflection;using Arena.Original;using NUnit.Framework;using UnityEngine;
namespace Arena.Tests{
public sealed class OriginalSessionDisconnectedItemTests{
const BindingFlags P=BindingFlags.Instance|BindingFlags.NonPublic;
sealed class Nav:IOriginalWorldNavigation{public OriginalPoint HeroSpawn=>new OriginalPoint(135,1000);public long NavigationRevision=>0;public bool IsWalkable(double x,double y,double r)=>true;public bool SegmentClear(OriginalPoint a,OriginalPoint b,double r)=>true;public OriginalPoint[] FindPath(OriginalPoint a,OriginalPoint b,double r)=>new[]{b};public bool SetDoodadAlive(int id,bool alive)=>true;}
static T Load<T>(string n)=>JsonUtility.FromJson<T>(File.ReadAllText(Path.Combine(Application.dataPath,"Arena/Data/lia39-"+n+".json")));
static object Player(OriginalSession s)=>((IList)typeof(OriginalSession).GetField("players",P).GetValue(s))[1];
static OriginalWorld World(OriginalSession s)=>(OriginalWorld)typeof(OriginalSession).GetField("world",P).GetValue(s);
static OriginalInventory Inventory(OriginalSession s)=>(OriginalInventory)Player(s).GetType().GetField("inventory").GetValue(Player(s));
static object Call(OriginalSession s,string n,params object[] a)=>typeof(OriginalSession).GetMethod(n,P).Invoke(s,a);
static OriginalSession Create(string hero,int round=5){var native=Load<OriginalNativeCatalog>("native126");var obs=Load<OriginalObservedCatalog>("observed126");var options=OriginalMatchOptions.ForDifficulty(OriginalDifficulty.Standard);options.curse=false;
var s=new OriginalSession(Load<OriginalMatchCatalog>("match"),Load<OriginalItemCatalog>("items"),Load<OriginalCombatCatalog>("combat"),Load<OriginalDuelCatalog>("duels"),new string('a',64),options,123);s.ConfigureProgression(native,obs);s.ConfigureWorld(new Nav(),native,Array.Empty<OriginalWorldDoodadView>(),obs);s.ConfigureItems(native,Load<OriginalObservedItemCatalog>("observed-items126"),Load<OriginalItemPassiveCatalog>("item-passives"));
Assert.That(s.Apply(0,new OriginalSessionCommand{sequence=1,kind=OriginalSessionCommandKind.SelectHero,heroId=hero=="H008"?"N0A0":"H008"}),Is.EqualTo(OriginalSessionReplyCode.Accepted));
Assert.That(s.Apply(22,new OriginalSessionCommand{sequence=1,kind=OriginalSessionCommandKind.Hello,protocol=OriginalSession.Protocol,contentHash=s.Snapshot().contentHash}),Is.EqualTo(OriginalSessionReplyCode.Accepted));
Assert.That(s.Apply(22,new OriginalSessionCommand{sequence=2,kind=OriginalSessionCommandKind.SelectHero,heroId=hero}),Is.EqualTo(OriginalSessionReplyCode.Accepted));Assert.That(s.Apply(22,new OriginalSessionCommand{sequence=3,kind=OriginalSessionCommandKind.LobbyReady,ready=true}),Is.EqualTo(OriginalSessionReplyCode.Accepted));
Assert.That(s.Apply(0,new OriginalSessionCommand{sequence=2,kind=OriginalSessionCommandKind.LobbyReady,ready=true}),Is.EqualTo(OriginalSessionReplyCode.Accepted));Assert.That(s.Apply(0,new OriginalSessionCommand{sequence=3,kind=OriginalSessionCommandKind.Start}),Is.EqualTo(OriginalSessionReplyCode.Accepted));
// Controlled combat phase isolates the AI order consumer from wave spawns.
var match=(OriginalMatch)typeof(OriginalSession).GetField("match",P).GetValue(s);typeof(OriginalMatch).GetProperty("Round").SetValue(match,round);typeof(OriginalMatch).GetProperty("Phase").SetValue(match,OriginalMatchPhase.Combat);World(s).SetUnitState(1,invulnerable:true);World(s).SetUnitState(2,invulnerable:true);Inventory(s).GrantResources(100000,100);return s;}
static void Prepare(OriginalSession s,bool disconnect=true,bool boostMana=true){if(disconnect)Assert.That(s.Disconnect(22),Is.True);if(!boostMana)return;var a=World(s).UnitState(2);var profile=a.profile;profile.maxMana=10000;Assert.That(World(s).UpdateProfile(2,profile,a.health,10000),Is.True);}
static void Enemy(OriginalSession s,double dx=200){var a=World(s).UnitState(2);World(s).AddUnit(9001,0,"hfoo",new OriginalWorldUnitProfile{maxHealth=10000,maxMana=1000,collisionRadius=8},new OriginalPoint(a.position.x+dx,a.position.y));}
static void Advance(OriginalSession s,double seconds){for(double left=seconds;left>1e-8;left-=.05){s.Advance(Math.Min(.05,left));s.DrainEvents();Assert.That(s.HaltReason,Is.Null);}}
static OriginalItemInstance Equip(OriginalSession s,string id){var candidate=Inventory(s).Copy();var item=candidate.CreateInstance(id);Assert.That(candidate.TryPickup(item).Applied,Is.True);Assert.That(Call(s,"ApplyEquipmentProfile",Player(s),candidate,World(s).UnitState(2)),Is.True);Player(s).GetType().GetField("inventory").SetValue(Player(s),candidate);return item;}
static OriginalItemUseView Use(OriginalSession s,string id)=>s.Snapshot().players.Single(x=>x.slot==2).itemUses.Single(x=>x.itemId==id);
[TestCase("H008",26,"I05A"),TestCase("N0A0",24,"I05P"),TestCase("H024",18,"I015"),TestCase("H024",20,"I045")]
public void PublicDisconnectUsesItsActualPurchasedTargetItem(string hero,int index,string id){var s=Create(hero);Assert.That(Call(s,"TryDisconnectedShoppingPurchase",Player(s),index),Is.True);Assert.That(Inventory(s).HeroSlots.Any(x=>x?.itemId==id),Is.True);Enemy(s);Prepare(s);Assert.That(Use(s,id).code,Is.EqualTo(OriginalItemUseCode.Ready));Advance(s,.75);Assert.That(Use(s,id).cooldownRemaining,Is.GreaterThan(0),id);Assert.That(s.Snapshot().players.Single(x=>x.slot==2).connected,Is.False);}
[Test]public void SpaceBootsKeepTheSourceNormalWaveGateAndConnectedPlayersAreNotAutomated(){foreach(bool disconnected in new[]{false,true}){var s=Create("N0A0",1);Equip(s,"I05P");Enemy(s);Prepare(s,disconnected);Advance(s,.75);Assert.That(Use(s,"I05P").cooldownRemaining,Is.Zero);}}
[Test]public void NoEnemyInsideTheSourceSelectorRadiusDoesNotSpendAReadyTargetItem(){var s=Create("H008");Equip(s,"I05A");Enemy(s,1000);Prepare(s);Advance(s,.5);Assert.That(Use(s,"I05A").cooldownRemaining,Is.Zero);}
[TestCase("I00T",.6),TestCase("I00V",.5),TestCase("I07P",.8),TestCase("I08D",.75)]public void SourceHealthTargetItemUsesAnInjuredHeroAndRejectsFullAllies(string id,double threshold){var s=Create("H008");Equip(s,id);Prepare(s);var ally=World(s).UnitState(1);World(s).SetUnitState(1,invulnerable:false);World(s).UpdateProfile(1,ally.profile,ally.profile.maxHealth*threshold*.9,ally.mana);Advance(s,.75);Assert.That(Use(s,id).cooldownRemaining,Is.GreaterThan(0));var full=Create("H008");Equip(full,id);Prepare(full);Advance(full,.5);Assert.That(Use(full,id).cooldownRemaining,Is.Zero);}
[Test]public void SourceWardEnemyGateUsesTheCasterPointInsteadOfTheEnemyPosition(){var s=Create("H008");Equip(s,"I021");Enemy(s);Prepare(s,true,false);var actor=World(s).UnitState(2);Assert.That(Use(s,"I021").code,Is.EqualTo(OriginalItemUseCode.Ready),JsonUtility.ToJson(Use(s,"I021")));Advance(s,.75);var wards=World(s).Snapshot().units.Where(x=>x.kind==OriginalWorldUnitKind.Summon&&x.rawcode=="ohwd").ToArray();Assert.That(wards.Length,Is.EqualTo(1),JsonUtility.ToJson(s.Snapshot()));var ward=wards[0];double dx=ward.position.x-actor.position.x,dy=ward.position.y-actor.position.y;Assert.That(dx*dx+dy*dy,Is.LessThanOrEqualTo(100*100));Assert.That(Inventory(s).HeroSlots.All(x=>x?.itemId!="I021"),Is.True);}
[Test]public void DisconnectedSkillHelperAcceptsAValidFarPointThroughTheSharedIntent(){var s=Create("N0A0");Prepare(s,true,false);var a=World(s).UnitState(2);var target=new OriginalPoint(a.position.x+1200,a.position.y+1);Assert.That(Call(s,"DisconnectedAiCast",Player(s),"A15W",target,new[]{"A15W"}),Is.True);Assert.That(World(s).UnitState(2).mana,Is.EqualTo(a.mana));Assert.That(World(s).UnitState(2).order,Is.EqualTo(OriginalWorldOrder.Move));Advance(s,.2);Assert.That(World(s).UnitState(2).mana,Is.EqualTo(a.mana));Advance(s,5);Assert.That(World(s).UnitState(2).castSequence,Is.EqualTo(1));Assert.That(s.Snapshot().players.Single(x=>x.slot==2).abilities.Single(x=>x.id=="A15W").cooldownRemaining,Is.GreaterThan(0));}
[Test]public void DisconnectedNoTargetSkillKeepsItsExistingImmediateCastConsumer(){var s=Create("H008");Prepare(s,true,false);var a=World(s).UnitState(2);Assert.That(Call(s,"DisconnectedAiCast",Player(s),"A05N",a.position,new[]{"A05N"}),Is.True);Assert.That(World(s).UnitState(2).castSequence,Is.EqualTo(1));Assert.That(World(s).UnitState(2).order,Is.EqualTo(OriginalWorldOrder.None));}
[Test]public void NativeShockwaveUnitBridgeUsesSelectedEnemyCoordinatesAndCommitsFourHundredManaOnce(){var s=Create("H008");var item=Equip(s,"I02C");Enemy(s);Prepare(s);var before=World(s).UnitState(2);Assert.That(Use(s,"I02C").targetMode,Is.EqualTo(OriginalAbilityTargetMode.Point));for(int i=0;i<20&&Use(s,"I02C").cooldownRemaining==0;i++)Advance(s,.05);Assert.That(Use(s,"I02C").cooldownRemaining,Is.GreaterThan(0));Assert.That(World(s).UnitState(2).mana,Is.EqualTo(before.mana-400).Within(1e-8));Advance(s,.4);Assert.That(World(s).UnitState(9001).health,Is.LessThan(10000));Assert.That(Inventory(s).HeroSlots.Single(x=>x!=null).instanceId,Is.EqualTo(item.instanceId));}
[Test]public void NativeShockwaveBridgeKeepsTheSourceEnemySelectionRange(){var s=Create("H008");Equip(s,"I02C");Enemy(s,1000);Prepare(s);Advance(s,.75);Assert.That(Use(s,"I02C").cooldownRemaining,Is.Zero);Assert.That(World(s).UnitState(9001).health,Is.EqualTo(10000));}
}}





